function [dipole_av_diag,dipole_av_diag_f,mag_av_diag,mag_av_diag_f,...
             dipole_av_coh ,  mag_av_coh]= ori_av_fn( ...
        mu_ex,m_ex,mu_ex2,m_ex2,conj_lg,pol_set,mag_set,calc_OD,calc_coh)
%calculates dipole averages which will be needed for third order
%spectroscopy with additional magnetic and well as electric dipole
%interactions.

N = size(mu_ex,1); N2 =  size(mu_ex2,3);

if ~exist('calc_OD','var') %calculate mixings of the form V_j1 rho V_j2
    calc_OD = false;
end
if ~exist('cal_coh','var') %include averages relevant for coherence contributions
    calc_coh = false;
end

mpol_comb{1} =  cond_conj([mag_set(1,:);pol_set(2:4,:)],conj_lg);
mpol_comb{2} =  cond_conj([pol_set(1,:);mag_set(2,:);pol_set(3:4,:)],conj_lg);
mpol_comb{3} =  cond_conj([pol_set(1:2,:);mag_set(3,:);pol_set(4,:)],conj_lg);
mpol_comb{4} =  cond_conj([pol_set(1:3,:);mag_set(4,:)],conj_lg);
pol_set = cond_conj(pol_set,conj_lg);

if ~calc_OD
    
    dipole_av_diag = zeros(N,N); dipole_av_diag_f =  zeros(N,N,N2);
    mag_av_diag = zeros(N,N); mag_av_diag_f =  zeros(N,N,N2);
     if calc_coh
         dipole_av_coh = zeros(N,N*(N-1)/2);
         mag_av_coh = zeros(N,N*(N-1)/2);
     else
         dipole_av_coh = [];
         mag_av_coh = [];         
     end

for j = 1:N
    
    if calc_coh %calculate V_{g,j} V_{j,f} V_{f,j} V_{j,g} shit       
        for f = 1:N*(N-1)/2
            
            dipole_av_coh(j,f) = tensor_av(cond_conj([mu_ex(j,:);mu_ex2(j,:,f)...
                                  ;mu_ex2(j,:,f);mu_ex(j,:)],conj_lg), pol_set);
            mag_av_coh(j,f) = tensor_av(cond_conj([m_ex(j,:);mu_ex2(j,:,f)...
                               ;mu_ex2(j,:,f);mu_ex(j,:)],conj_lg),mpol_comb{1})+...
      tensor_av(cond_conj([mu_ex(j,:);m_ex2(j,:,f)...
                           ;mu_ex2(j,:,f);mu_ex(j,:)],conj_lg),mpol_comb{2})+...
      tensor_av(cond_conj([mu_ex(j,:);mu_ex2(j,:,f)...
                        ;m_ex2(j,:,f);mu_ex(j,:)],conj_lg), mpol_comb{3})+...
     tensor_av(cond_conj([mu_ex(j,:);mu_ex2(j,:,f)...
                        ;mu_ex2(j,:,f);m_ex(j,:)],conj_lg),mpol_comb{4});       
        end
    end
    
    for j2 = 1:N
dipole_av_diag(j,j2) = tensor_av(cond_conj([mu_ex(j,:);mu_ex(j,:);mu_ex(j2,:);mu_ex(j2,:)],conj_lg),...
                        pol_set);
                    
mag_av_diag(j,j2) = tensor_av(cond_conj([m_ex(j,:);mu_ex(j,:);mu_ex(j2,:);mu_ex(j2,:)],...
                        conj_lg),mpol_comb{1})+...
      tensor_av(cond_conj([mu_ex(j,:);m_ex(j,:);mu_ex(j2,:);mu_ex(j2,:)],conj_lg),...
                        mpol_comb{2})+...
      tensor_av(cond_conj([mu_ex(j,:);mu_ex(j,:);m_ex(j2,:);mu_ex(j2,:)],conj_lg),...
                        mpol_comb{3})+...
     tensor_av(cond_conj([mu_ex(j,:);mu_ex(j,:);mu_ex(j2,:);m_ex(j2,:)],conj_lg),...
                        mpol_comb{4});
                    
                    for f=1:N2
dipole_av_diag_f(j,j2,f)  = tensor_av(cond_conj([mu_ex(j,:);mu_ex(j,:);...
                                 mu_ex2(j2,:,f);mu_ex2(j2,:,f)],conj_lg),pol_set);
                    
mag_av_diag_f(j,j2,f) = tensor_av(cond_conj([m_ex2(j,:);mu_ex(j,:);mu_ex2(j2,:,f);mu_ex2(j2,:,f)],conj_lg),...
                        mpol_comb{1})+...
                    tensor_av(cond_conj([mu_ex(j,:);m_ex2(j,:);mu_ex2(j2,:,f);mu_ex2(j2,:,f)],conj_lg),...
                        mpol_comb{2})+...
                    tensor_av(cond_conj([mu_ex(j,:);mu_ex2(j,:);m_ex2(j2,:,f);mu_ex2(j2,:,f)],conj_lg),...
                        mpol_comb{3})+...
                    tensor_av(cond_conj([mu_ex(j,:);mu_ex2(j,:);mu_ex2(j2,:,f);m_ex2(j2,:,f)],conj_lg),...
                        mpol_comb{4});                    
                    
                    end
    end
end

else
    
   dipole_av_diag = zeros(N,N,N,N); dipole_av_diag_f =  zeros(N,N,N,N,N*(N-1)/2);
mag_av_diag = zeros(N,N,N,N); mag_av_diag_f =  zeros(N,N,N,N,N*(N-1)/2);
    if calc_coh %calculate V_{g,j} V_{j,f} V_{f,j} V_{j,g} shit       

            dipole_av_coh = zeros(N,N*(N-1)/2,N*(N-1)/2,N);
            mag_av_coh = zeros(N,N*(N-1)/2,N*(N-1)/2,N);
  
    end

for j = 1:N
    for j2 = 1:N
        for j3=1:N
            for j4=1:N
dipole_av_diag(j,j2,j3,j4) = tensor_av(cond_conj([mu_ex(j,:);mu_ex(j2,:);mu_ex(j3,:);mu_ex(j4,:)],conj_lg),...
                        pol_set);
                    
mag_av_diag(j,j2,j3,j4) = tensor_av(cond_conj([m_ex(j,:);mu_ex(j2,:);mu_ex(j3,:);mu_ex(j4,:)],conj_lg),...
                        mpol_comb{1})+...
                    tensor_av(cond_conj([mu_ex(j,:);m_ex(j2,:);mu_ex(j3,:);mu_ex(j4,:)],conj_lg),...
                        mpol_comb{2})+...
                    tensor_av(cond_conj([mu_ex(j,:);mu_ex(j2,:);m_ex(j3,:);mu_ex(j4,:)],conj_lg),...
                        mpol_comb{3})+...
                    tensor_av(cond_conj([mu_ex(j,:);mu_ex(j2,:);mu_ex(j3,:);m_ex(j4,:)],conj_lg),...
                        mpol_comb{4});
                    
                    for f=1:N2
dipole_av_diag_f(j,j2,j3,j4,f)  = tensor_av(cond_conj([mu_ex(j,:);mu_ex(j2,:);...
                                 mu_ex2(j3,:,f);mu_ex2(j4,:,f)],conj_lg),pol_set);
                    
mag_av_diag_f(j,j2,j3,j4,f) = tensor_av(cond_conj([m_ex2(j,:);mu_ex(j2,:);mu_ex2(j3,:,f);mu_ex2(j4,:,f)],conj_lg),...
                        mpol_comb{1})+...
                    tensor_av(cond_conj([mu_ex(j,:);m_ex2(j2,:);mu_ex2(j3,:,f);mu_ex2(j4,:,f)],conj_lg),...
                        mpol_comb{2})+...
                    tensor_av(cond_conj([mu_ex(j,:);mu_ex2(j2,:);m_ex2(j3,:,f);mu_ex2(j4,:,f)],conj_lg),...
                        mpol_comb{3})+...
                    tensor_av(cond_conj([mu_ex(j,:);mu_ex2(j2,:);mu_ex2(j3,:,f);m_ex2(j4,:,f)],conj_lg),...
                        mpol_comb{4});                    
                    
                    end
            end
        end
    end
end    
end
end

function out=cond_conj(x_set,lg)

    out  = x_set;
    out(lg,:) = conj(x_set(lg,:));

end