function aver = tensor_av(A,B)
%find average of the form <A_1 dot B_1 * A_2 dot B_2 ... *A_n dot B_n>
if size(A,1) ~= size(B,1) || size(B,2)~=3 ||size(A,2)~=3 
    error('input must be two sets of matricies of same size in dim 1 and size 3 in dim2')
end

if size(A,1) == 2
    aver = 1/3*dott(A(1,:),A(2,:))*dott(B(1,:),B(2,:));
elseif size(A,1) == 3
    aver = 1/6*(dott(A(1,:),cross_simp(A(2,:),A(3,:)))*dott(B(1,:),cross_simp(B(2,:),B(3,:))));
elseif size(A,1) == 4
    tmp1 = dott(A(1,:),A(2,:))*dott(A(3,:),A(4,:));
    tmp2 = dott(A(1,:),A(3,:))*dott(A(2,:),A(4,:));
    tmp3 = dott(A(1,:),A(4,:))*dott(A(3,:),A(2,:));
    
aver =         (4*tmp1 - tmp2 - tmp3)*dott(B(1,:),B(2,:))*dott(B(3,:),B(4,:));
aver = aver + (-tmp1 + 4*tmp2 - tmp3)*dott(B(1,:),B(3,:))*dott(B(2,:),B(4,:));
aver = aver + (-tmp1 - tmp2 + 4*tmp3)*dott(B(1,:),B(4,:))*dott(B(3,:),B(2,:));   
            aver = aver /30;
            
elseif size(A,1) == 5 %10 terms
    %12345, 13245
%     A12 = dott(A(1,:),A(2,:)); A13 = dott(A(1,:),A(3,:));
%     A14 = dott(A(1,:),A(4,:)); A15 = dott(A(1,:),A(5,:));
%     A23 = dott(A(2,:),A(3,:)); A24 = dott(A(2,:),A(4,:));
%     A25 = dott(A(2,:),A(5,:)); A34 = dott(A(3,:),A(4,:));
%     A35 = dott(A(3,:),A(5,:)); A45 = dott(A(4,:),A(5,:));
%     
    
    AC23 = cross_simp(A(2,:),A(3,:)); AC24 = cross_simp(A(2,:),A(4,:));  
    AC25 = cross_simp(A(2,:),A(5,:)); 
    AC34 = cross_simp(A(3,:),A(4,:)); AC35 = cross_simp(A(3,:),A(5,:));
    AC45 = cross_simp(A(4,:),A(5,:)); 

    BC45 = cross_simp(B(4,:),B(5,:)); BC35 = cross_simp(B(3,:),B(5,:));
    BC25 = cross_simp(B(2,:),B(5,:)); BC34 = cross_simp(B(3,:),B(4,:)); 
    BC24 = cross_simp(B(2,:),B(4,:)); BC23 = cross_simp(B(2,:),B(3,:));    
    
     aver = dott(A(1,:),A(2,:))*dott(A(3,:),AC45)*...
            dott(B(1,:),B(2,:))*dott(B(3,:),BC45)+...
            dott(A(1,:),A(3,:))*dott(A(2,:),AC45)*...
            dott(B(1,:),B(3,:))*dott(B(2,:),BC45);
      %14235,15234   
aver = aver+ dott(A(1,:),A(4,:))*dott(A(2,:),AC35)*...
            dott(B(1,:),B(4,:))*dott(B(2,:),BC35)+...
            dott(A(1,:),A(5,:))*dott(A(2,:),AC34)*...
            dott(B(1,:),B(5,:))*dott(B(2,:),BC34);    
     %23145,24135   
aver = aver+dott(A(2,:),A(3,:))*dott(A(1,:),AC45)*...
            dott(B(2,:),B(3,:))*dott(B(1,:),BC45)+...
            dott(A(2,:),A(4,:))*dott(A(1,:),AC35)*...
            dott(B(2,:),B(4,:))*dott(B(1,:),BC35);         
 %25134, 34125
aver = aver+dott(A(2,:),A(5,:))*dott(A(1,:),AC34)*...
            dott(B(2,:),B(5,:))*dott(B(1,:),BC34)+...
            dott(A(3,:),A(4,:))*dott(A(1,:),AC25)*...
            dott(B(3,:),B(4,:))*dott(B(1,:),BC25);   
   %35124, 45123     
aver = aver+dott(A(3,:),A(5,:))*dott(A(1,:),AC24)*...
            dott(B(3,:),B(5,:))*dott(B(1,:),BC24)+...
            dott(A(4,:),A(5,:))*dott(A(1,:),AC23)*...
            dott(B(4,:),B(5,:))*dott(B(1,:),BC23);  

%       aver = dott(A(1,:),A(2,:))*dott(A(3,:),cross_simp(A(4,:),A(5,:)))*...
%             dott(B(1,:),B(2,:))*dott(B(3,:),cross_simp(B(4,:),B(5,:)))+...
%             dott(A(1,:),A(3,:))*dott(A(2,:),cross_simp(A(4,:),A(5,:)))*...
%             dott(B(1,:),B(3,:))*dott(B(2,:),cross_simp(B(4,:),B(5,:)));
%       %14235,15234   
% aver = aver+ dott(A(1,:),A(4,:))*dott(A(2,:),cross_simp(A(3,:),A(5,:)))*...
%             dott(B(1,:),B(4,:))*dott(B(2,:),cross_simp(B(3,:),B(5,:)))+...
%             dott(A(1,:),A(5,:))*dott(A(2,:),cross_simp(A(3,:),A(4,:)))*...
%             dott(B(1,:),B(5,:))*dott(B(2,:),cross_simp(B(3,:),B(4,:)));    
%      %23145,24135   
% aver = aver+dott(A(2,:),A(3,:))*dott(A(1,:),cross_simp(A(4,:),A(5,:)))*...
%             dott(B(2,:),B(3,:))*dott(B(1,:),cross_simp(B(4,:),B(5,:)))+...
%             dott(A(2,:),A(4,:))*dott(A(1,:),cross_simp(A(3,:),A(5,:)))*...
%             dott(B(2,:),B(4,:))*dott(B(1,:),cross_simp(B(3,:),B(5,:)));         
%  %25134, 34125
% aver = aver+dott(A(2,:),A(5,:))*dott(A(1,:),cross_simp(A(3,:),A(4,:)))*...
%             dott(B(2,:),B(5,:))*dott(B(1,:),cross_simp(B(3,:),B(4,:)))+...
%             dott(A(3,:),A(4,:))*dott(A(1,:),cross_simp(A(2,:),A(5,:)))*...
%             dott(B(3,:),B(4,:))*dott(B(1,:),cross_simp(B(2,:),B(5,:)));   
%    %35124, 45123     
% aver = aver+dott(A(3,:),A(5,:))*dott(A(1,:),cross_simp(A(2,:),A(4,:)))*...
%             dott(B(3,:),B(5,:))*dott(B(1,:),cross_simp(B(2,:),B(4,:)))+...
%             dott(A(4,:),A(5,:))*dott(A(1,:),cross_simp(A(2,:),A(3,:)))*...
%             dott(B(4,:),B(5,:))*dott(B(1,:),cross_simp(B(2,:),B(3,:))); 

        aver = aver/30;
else
    error('rank must be < 6')
end
end
    function out = dott(AA,BB) %dot conjugate transposes....
       
        out = AA(1)*BB(1) + AA(2)*BB(2) + AA(3)*BB(3);
        
    end
     function out = cross_simp(AA,BB) %dot conjugate transposes....
       
        out = [AA(2)*BB(3) - AA(3)*BB(2) ;AA(3)*BB(1) - AA(1)*BB(3)...
                ;-AA(2)*BB(1) + AA(1)*BB(2)];
        
    end   
    